name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: wdk710-build-environment
        registry: ghcr.io
        addLatest: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
